services:
  - type: web
    name: wikiband-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_CLIENT
        value: postgres
      - key: DB_SSL
        value: "true"
      - key: DB_SSL_REJECT_UNAUTHORIZED
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
